### ISSUE TITLE
Accept String and other datatypes in arithmetic FILTER expressions

### ISSUE THREAD

**Issue by stuehmer** [play-project/play-dcep#17]
Improve the handling of literals' types in FILTER expressions such as `FILTER(?pollutant = "O3NO2" && ?pollutionRate >= 6 && abs(?latitude1 - ?latitude2) < 10)`

Current behaviour:
- All values in arithmetic expressions are expected to be numbers which is fine for  `"1.0"` and  `1.0`
- This causes unexpected behavour with things like `"O3NO2"`

Expected behaviour:
- use the datatypes as in SPARQL, e.g.: `1.0` is a number `"O3NO2"` is a String, `"1.0"^^xsd:double` is a number and `"string"^^xsd:double` must cause a parsing error

**Comment by obermeier** [comment]
Datatypes are used as parsed from source, e.g. `1.2`, `200` and `"a string"`.  If wrong dataype is given  unknown datatype exceptions is thrown or log message is generated depending on jena implementation. (E.g. java.lang.RuntimeException: "abc"^^http://www.w3.org/2001/XMLSchema#floatunknown datatype in HAVING expression or "[main] WARN  c.hp.hpl.jena.sparql.expr.NodeValue - Datatype format exception: "JEANS"^^xsd:int" in FILTER expression.
